---
- name: Add PGDG apt repository
  ansible.builtin.import_tasks: repo.yml

- name: Install PostgreSQL packages
  ansible.builtin.import_tasks: install.yml

- name: Prepare PostgreSQL data directory
  ansible.builtin.import_tasks: prepare.yml
