---
galaxy_info:
  role_name: etcd
  author: dify-pg-ha
  description: Deploy etcd cluster as DCS for Patroni
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
dependencies:
  - role: os_prep
