---
- name: Render haproxy configuration
  ansible.builtin.include_tasks: render.yml
  tags: [haproxy, haproxy-config]

- name: Apply HAProxy K8s resources
  ansible.builtin.include_tasks: apply.yml
  tags: [haproxy, haproxy-install, haproxy-config]
