---
galaxy_info:
  role_name: haproxy
  author: postgres-ha
  description: Deploy HAProxy to Kubernetes as routing layer to PostgreSQL primary
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
dependencies: []
