---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: [os_prep, os_prep-install]

- name: Install required base packages
  ansible.builtin.apt:
    name: "{{ os_prep_required_packages }}"
    state: present
  tags: [os_prep, os_prep-install]
