---
- name: Install etcd binaries
  ansible.builtin.import_tasks: install.yml

- name: Configure etcd
  ansible.builtin.import_tasks: configure.yml

- name: Start etcd service
  ansible.builtin.import_tasks: start.yml

- name: Verify etcd cluster health
  ansible.builtin.import_tasks: verify.yml
