---
etcd_user: etcd
etcd_group: etcd
etcd_install_dir: /usr/local/bin
etcd_data_dir: /u01/etcd
etcd_config_dir: /etc/etcd
etcd_client_port: "{{ etcd_client_port | default(2379) }}"
etcd_peer_port: "{{ etcd_peer_port | default(2380) }}"
